config/routes.rb
Tester::Application.routes.draw do
  get "foods/search"

  get "foods/view"

  get "log_out" => "sessions#destroy", :as => "log_out"
  get "log_in" => "sessions#new", :as => "log_in"

  get "profile" => "users#view", :as => "profile"

  get "users/new"
  get "users/view"

  get "goods/view"
  get "goods/search"

  get "users/new_food"
  get "users/delete_food"

  root :to => 'foods#search'
  resources :users
  resources :sessions

end

app/models/food.rb
class Food < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_and_belongs_to_many :foods

  attr_accessible :email, :password, :password_confirmation
  
  attr_accessor :password
  before_save :encrypt_password
  
  validates_confirmation_of :password
  validates_presence_of :password, :on => :create
  validates_presence_of :email
  validates_uniqueness_of :email
  validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, :on => :create

  
  def self.authenticate(email, password)
    user = find_by_email(email)
    if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
      user
    else
      nil
    end
  end
  
  def encrypt_password
    if password.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  helper_method :current_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end  
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def search
  	foods = Food.all
  	@food_names = []
  	foods.each do |food|
  		@food_names.push(food.food_name)
  	end
  end

  def view
  	if params[:query] != nil
      search_name = params[:query]
    	@food_to_disp = Food.find_by_food_name(search_name)
    	@food_attrs = Food.column_names
    else
      @food_to_disp = Food.find(params[:food_id])
      @food_attrs = Food.column_names
    end
  end
end

app/controllers/goods_controller.rb
class GoodsController < ApplicationController
	def view
		doc = Nokogiri::XML(File.open("doc/usda.xml"))
		@search_q = params[:query]
		mod_search = ""
		
		# Process query for ' and " characters
		@search_q.each_char do |i|
			if (i == '"')
				mod_search = mod_search+"\""
			else
				mod_search = mod_search + i
			end
		end

		@items = doc.xpath('/food_database/Description[food_name="'+@search_q+'"]/*')




		# @items.each do |item|
		# 	@attrs = item.children()
		# 	@attrs.each do |attr|
		# 		if (attr.name == "food_name" && attr.content == params[:query].to_s())
		# 			@result = @attrs
		# 		end
		# 	end
		# end	




		# @blahstwo = @blahs[params[:q].to_i()]
		# @results = @blahstwo.children()

		# @results = @blahs.children()[params[:q].to_i()]
		# rdf:Description['+params[:q].to_s()+']/*')
	end

	def search
		doc = Nokogiri::XML(File.open("doc/usda.xml"))
		@completions = doc.xpath('/food_database/Description/food_name')
		@names = Array.new
		@completions.each do |food|
			@names.push(food.content)
		end
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end

	def create
	  user = User.authenticate(params[:email], params[:password])
	  if user
	    session[:user_id] = user.id
	    redirect_to root_url, :notice => "Logged in!"
	  else
	    flash.now.alert = "Invalid email or password"
	    render "new"
	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to root_url, :notice => "Logged out!"
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
	 @user = User.new
	end

	def create
	  @user = User.new(params[:user])
	  if @user.save
	  	session[:user_id] = @user.id
	    redirect_to root_url, :notice => "Signed up!"
	  else
	    render "new"
	  end
	end

	def view
		if !current_user
			redirect_to root_url, :notice => "You must be logged in"
		end
	end

	def new_food
		current_user.foods.push(Food.find(params[:food_id]))
		redirect_to profile_path
	end

	def delete_food
		current_user.foods.delete(Food.find(params[:food_id]))
		redirect_to profile_path
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/goods_helper.rb
module GoodsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/search.html.erb
<!-- <div class="hero-unit"> -->
	<div class="row">
		<div class="span12" align="center"><h1>MyBites</h1></div>
	</div>
	<div class="row">
		<div class="span12" align="center"><h2>Start Tracking Your Nutrition Now!</h2></div>
	</div>
	<%= form_tag('/foods/view', :method => "get") do %>
	  <br /><br /><br />
	  <div align="center">
	  	<%= text_field_tag :query, nil, :class => "input-xlarge search-query-home bigger-search", :placeholder => "Find your food...", :'data-provide' => "typeahead", :autocomplete => "off" %>
	  	<%= submit_tag "Search", :class => "btn btn-primary btn-large", :id => "search-bar" %>
	  </div>
	<% end %>
<!-- </div> -->

<div class="row">
	<div class="span4">
		<ul class="thumbnails">
			<div class="span4 offset4">
				<li>
					<a href="#" class="thumbnail"><img src="http://placehold.it/360x268" alt=""></a>
				</li>
			</div>
		</ul>
	</div>
</div>

<script> 
$(document).ready(function(){
	$('#query').typeahead({ // Typeahead for Autocomplete
		source: <%= @food_names.to_json.html_safe %>,
		items: 10
	}); 

	$('#search-bar').click(function(){ // Error Messages
		$('.error').hide();
		var hasError = false;
		var knownBase = <%= @food_names.to_json.html_safe %>;
		var searchVal = $('#query').val();
		if(searchVal == ''){
			$('#search-bar').after('<div class="error">Don\'t leave this blank.</div>');
			hasError = true;
		}
		else if(knownBase.indexOf(searchVal) <= -1){
			$('#search-bar').after('<div class="error">Please choose a food item from the autocomplete menu.</div>');
			hasError = true;			
		}
		$('.error').css({'color':'red', 'font-weight':'bold'});		
		if (hasError == true) {return false;}
	});
});
</script>

app/views/foods/view.html.erb
<div class="row">
	<div class="span4">
		<h2><%= link_to "<-- Search for more foods", :action => "search" %></h2>
	</div>
	<% if current_user %>
		<div class="span4">
			<% if !current_user.foods.include?(@food_to_disp) %>
				<h2><%= link_to "Track", :controller => "users", :action => "new_food", :food_id => @food_to_disp.id %> this food?</h2>
			<% end %>
		</div>
		<div class="span4">
			<h2><a href="/profile">Foods currently tracking</a></h2>
		</div>
	<% else %>
		<div class="span4">
				<h2><a href="/log_in">Log in</a> to track this food item!</h2>
		</div>
	<% end %>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th><h3>Food Attribute</h3></th>
			<th><h3>Numeric Value</h3></th>
		</tr>
	</thead>
	<tbody>
		<% @food_attrs.each do |attribute| %>
				<% if attribute != "created_at" && attribute != "updated_at" %>
					<tr>
						<td><%= attribute %></td>
						<td><%= @food_to_disp[attribute] %></td>
					</tr>
				<% end %>
		<% end %>
	</tbody>
</table>

app/views/goods/search.html.erb
<!-- <div class="hero-unit"> -->
	<div class="row">
		<div class="span12" align="center"><h1>MyBites</h1></div>
	</div>
	<div class="row">
		<div class="span12" align="center"><h2>Start Tracking Your Nutrition Now!</h2></div>
	</div>
	<%= form_tag('/goods/view', :method => "get") do %>
	  <br /><br /><br />
	  <div align="center">
	  	<%= text_field_tag :query, nil, :class => "input-xlarge search-query-home bigger-search", :placeholder => "Find your food...", :'data-provide' => "typeahead", :autocomplete => "off" %>
	  	<%= submit_tag "Search", :class => "btn btn-primary btn-large", :id => "search-bar" %>
	  </div>
	<% end %>
<!-- </div> -->

<div class="row">
	<div class="span4">
		<ul class="thumbnails">
			<div class="span4 offset4">
				<li>
					<a href="#" class="thumbnail"><img src="http://placehold.it/360x268" alt=""></a>
				</li>
			</div>
		</ul>
	</div>
</div>

<script> 
$(document).ready(function(){
	$('#query').typeahead({ // Typeahead for Autocomplete
		source: <%= @names.to_json.html_safe %>,
		items: 10
	}); 

	$('#search-bar').click(function(){ // Error Messages
		$('.error').hide();
		var hasError = false;
		var knownBase = <%= @names.to_json.html_safe %>;
		var searchVal = $('#query').val();
		if(searchVal == ''){
			$('#search-bar').after('<div class="error">Don\'t leave this blank.</div>');
			hasError = true;
		}
		else if(knownBase.indexOf(searchVal) <= -1){
			$('#search-bar').after('<div class="error">Please choose a food item from the autocomplete menu.</div>');
			hasError = true;			
		}
		$('.error').css({'color':'red', 'font-weight':'bold'});		
		if (hasError == true) {return false;}
	});
});
</script>

app/views/goods/view.html.erb
<div class="row">
	<div class="span4">
		<h2><%= link_to "<-- Search for more foods", :action => "search" %></h2>
	</div>
	<% if current_user %>
		<div class="span4">
			<h2><%= link_to "Track", :controller => "users", :action => "new_food" %> this food?</h2>
		</div>
	<% else %>
		<div class="span4">
				<h2><a href="/log_in">Log in</a> to track this food item!</h2>
		</div>
	<% end %>
</div>

<table class="table table-striped">
	<thead>
		<tr>
			<th><h3>Food Property</h3></th>
			<th><h3>Numeric Value</h3></th>
		</tr>
	</thead>
	<tbody>
		<% if (@items != nil) %>
			<% @items.each do |aspect| %>
				<% if (aspect.name != "text" && aspect.name != "type") %>
					<tr>
						<td><%= aspect.name %></td>
						<td><%= aspect.content %></td>
					</tr>
				<% end %>
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyBites</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <style>
  body {background-image: url('/assets/rough_diagonal.png');}
  </style>
</head>
<body>
<div class="navbar navbar-fixed-top">
	<div class="navbar-inner">
		<div class="container">
			<a class="brand" href="/">MyBites</a>
			<ul class="nav pull-right">
				<% if current_user %>
					<li><a href="/profile">Welcome, <%=current_user.email %>!</a></li>
					<li><%= link_to "Log Out", log_out_path %></li>
				<% else %>
					<li><a href="/users/new">Sign Up</a></li>
					<li><%= link_to "Log In", log_in_path %></li>
				<% end %>
			</ul>
		</div>
	</div>
</div>	
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>	
<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h3>The following errors were found: </h3>
      <ul>
        <% for message in @user.errors.full_messages %>
          <div class="error-messages-new"><li><%= message %></li></div>
        <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= f.label :email %>
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <%= f.submit :class => "btn btn-success" %>
<% end %>

app/views/users/view.html.erb
<p>Your email address is <%=current_user.email %></p>
<p>You are tracking <%= current_user.foods.length %> food(s). <p/>
<% if current_user.foods.length > 0 %>
	<p>Your food(s) are: </p>
	<table>
	<% current_user.foods.each do |food| %>
	<tr>
		<td><%= link_to food.food_name, :controller => "foods", :action=> "view", :food_id => food.id %> </p></td>
		<td><%= link_to "Stop tracking", :action => "delete_food", :food_id => food.id %></td>
	</tr>

	<% end %>
	</table>
<% end %>